name: load test
on: [workflow_dispatch]
jobs:
  load-test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm run test
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-results.txt
        path: results.txt